### ISSUE TITLE
Finish up vehicle parking updater

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#48]
This feature has actually been added by Helsinki in their fork but we extended it to allow you to fetch data from ParkAPI sources.

We decided that we want to combine the parking importer for cars and bicycle in order to reuse the logic.

The combined model should contain the following fields:

- Capacity, wheelchair-accessible capacity
- Available spaces, available wheelchair-accessible spaces
- Details URL
- Image URL
- Opening hours (in OSM format)
- Fee hours (in OSM format)
- Type
  - BICYCLE_PARKING_COVERED
  - BICYCLE_PARKING_UNCOVERED
  - BICYCLE_LOCKER
  - CAR_PARKING_LOT
  - MULTI_STOREY_CAR_PARK
  - UNDERGROUND_CAR_PARK
  - CARAVAN_PARKING_LOT (sorry, Herrenberg really wants this)
- Customer notes (multilingual)
- status
  - OPEN (even when outside of opening hours, just that it's not closed for construction. can you come up with a better name?)
  - TEMPORARILY_CLOSED

## Type
I think it would be wise to never directly compare agains the type when checking if a car/bicycle may enter this parking lot but rather add a `isCar` or `isBicycle` method to the enum.

## First implementation
To test the implementation, please see #55 for a data source.

WIP branch: https://github.com/mfdz/OpenTripPlanner/tree/car-park-updater

**Comment by flaktack** [comment]
Based on the above and Zuplin a proposed `VehicleParking` class:

```
/**
 * Vehicle parking locations, which may allow bicycle and/or car parking.
 */
@Builder
@Getter
@EqualsAndHashCode(of = "id")
public class VehicleParking {

    /**
     * The id of the vehicle parking, prefixed by the source(=feedId) so that it is unique.
     */
    private FeedScopedId id;

    private String name;

    /**
     * Note: x = Longitude, y = Latitude
     */
    private double x, y;

    /**
     * Whether this station has space available information updated in real-time.
     */
    private boolean realTimeData = true;

    /**
     * Modes which may park here.
     */
    private TraverseModeSet modes;

    private String detailsUrl;

    private String imageUrl;

    /**
     * Source specific type of the vehicle parking.
     */
    private String type;

    /**
     * Source specific tags of the vehicle parking, which describe the available features.
     * For example park_and_ride, or static_osm_data.
     */
    private List<String> tags;

    // TODO: this would need to be parsed from the OSM format
    private RepeatingTimePeriod openingHours;

    private RepeatingTimePeriod feeHours;

    private I18NString note;

    private VehicleParkingState state;

    // TODO: this could be derived from Capacity / Availability, but being explicit allows for handling cases where the exact capacity is unknown
    private boolean wheelchairAccessiblePlaces;

    private Capacity capacity;

    private Availability availability;

    public String toString() {
        return String.format(Locale.US, "VehicleParking(%s at %.6f, %.6f)", name, y, x);
    }

    /**
     * The total number of spaces by type. -1 indicates unknown.
     */
    @Data
    @Builder
    public static class Capacity {

        private int bicycleSpaces = -1;
        private int carSpaces = -1;
        private int wheelchairAccessibleSpaces = -1;
    }

    /**
     * The number of free spaces by type. -1 indicates unknown.
     */
    @Data
    @Builder
    public static class Availability {

        private int bicycleSpaces = -1;
        private int carSpaces = -1;
        private int wheelchairAccessibleSpaces = -1;
    }

    /**
     * The state of the vehicle parking. TEMPORARILY_CLOSED and CLOSED are different so
     * that it may be represented differently to the user.
     */
    public enum VehicleParkingState {OPERATIONAL, TEMPORARILY_CLOSED, CLOSED}
}
```

**Comment by flaktack** [comment]
Notes:
 * `modes` could be replaced with explicit `boolean`s for `bicyclePlaces` and `carPlaces`, which would pair well with `wheelchairAccessiblePlaces`

**Comment by leonardehrenfried** [comment]
>     * `modes` could be replaced with explicit `boolean`s for `bicyclePlaces` and `carPlaces`, which would pair well with `wheelchairAccessiblePlaces`

Yes, that would have been my only criticism: you could set the `traverseMode` to something ridiculous like TRANSIT.

**Comment by leonardehrenfried** [comment]
Also potentially useful: if you want to know if an OSM opening hours string is open right now you can use a lib that I wrote: https://github.com/leonardehrenfried/opening-hours-evaluator

**Comment by leonardehrenfried** [comment]
Do you have an implementation for `RepeatingTimePeriod`?

**Comment by flaktack** [comment]
[`RepeatingTimePeriod`](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/src/main/java/org/opentripplanner/common/RepeatingTimePeriod.java) already exists for turn restrictions. For the actual opening/closing times to be _really_ taken into account more work would need to be done, due to the fact that currently the access / egress legs are "shifted" based on what is required for the transit part of the trip.
https://github.com/opentripplanner/OpenTripPlanner/blob/4e17541d3213b9d443dd95f4e0bce079e1ac10d0/src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java#L125

If only an alert is displayed (`$name is closed after 5pm`), than this isn't a problem, but there would be "impossible" itineraries -- since the parking lot is closed -- and maybe no alternatives.

To excluded parking lots which may not be used in a given itinerary (are closed) somewhat more work would be required (this is a brief sketch, other approaches might work better)
 * `RepeatingTimePeriods` would need to be expanded and mapped into RAPTOR's "time window", which all transit time are handled relative to in seconds
    https://github.com/opentripplanner/OpenTripPlanner/blob/4e17541d3213b9d443dd95f4e0bce079e1ac10d0/src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java#L41
 * the vehicle parking's time restrictions needs to be aggregated into the actual access / egress paths
 * multiple access legs for the same stop would need to be handled with differing time restrictions -- currently only one is handled
    * states with differing time restrictions shouldn't dominate each other (or different parking lots?)
  * given the above time-based turn-restrictions _probably_ aren't handled correctly, which may also cause problems... but I haven't tested that

**Comment by leonardehrenfried** [comment]
We do want to have the ability to exclude closed parking lots but perhaps that would be a separate PR in order to not mix up the discussions. Or do you think it's wise to bundle the two discussions into two?

**Comment by flaktack** [comment]
Smaller tasks, PR are better, no need to bundle them together. :-)

I only mentioned those so that it is clear that there would be more things required.

**Comment by leonardehrenfried** [comment]
It's a good point and it reminds me that I haven't made a ticket for that. :)
